[package]
name = "erasurecode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liberasurecode = { path="../liberasurecode", version = "1.0.3"}
rayon = "1.5"
lazy_static = "1.4"
object-pool = "0.5"
